name: Scrape hreflang from URL and Commit if Changes Detected

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: "0 12 * * *"  # Corre el workflow diariamente al mediodía

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pyyaml

    - name: Scrape hreflang and save to YAML
      run: python scrape_hreflang.py

    - name: Check for changes
      run: |
        # Detecta si hay cambios después del scraping
        git diff --exit-code || echo "Hay cambios en los archivos"

    - name: Commit and push changes if there are any
      if: success() # Este paso solo se ejecuta si hay cambios
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add html/hreflang_links.yaml
        
        # Commit solo si hay cambios
        git commit -m "Update hreflang_links.yaml with latest scrape results" || echo "No changes to commit"
        
        # Push solo si el commit fue exitoso
        git push || echo "Nothing to push"
