on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */6 * * *' # At minute 0 past every 6th hour
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Action
      uses: actions/checkout@v4
    - name: Scrape Apple Security Releases page 
      run: |-
        curl -s "https://support.apple.com/en-us/100100" > https://github.com/Geek-MD/Auror/tree/html/apple_updates.html
    - name: Commit and push if the data has changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
