name: Scrape and Save HTML from hreflang URLs

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: "0 */6 * * *"  # Corre el workflow cada 6 horas

jobs:
  scrape_and_save_html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install requests pyyaml

    - name: Scrape URLs from hreflang_links.yaml and save HTML files
      run: |
        python scrape_and_save_html.py

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add html/*.html
        git commit -m "Updated HTML files for hreflang URLs"
        git push
