name: Scrape and Save HTML from hreflang URLs

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente
  schedule:
    - cron: "0 */6 * * *"  # Corre el workflow cada 6 horas

jobs:
  scrape_and_save_html:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install requests pyyaml

    - name: Scrape URLs from hreflang_links.yaml and save HTML files
      run: |
        python scrape_and_save_html.py

    - name: Check for changes
      run: |
        git add html/
        if git diff --cached --exit-code; then
          echo "No changes to commit"
          exit 0
        else
          echo "Changes detected, proceeding with commit"
        fi

    - name: Commit and push changes if any
      if: success()
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git commit -m "Updated HTML files with latest scrape results"
        git push
